# Generated by Django 4.2.27 on 2026-02-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('reservations', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date_emission'], 'verbose_name': 'Facture', 'verbose_name_plural': 'Factures'},
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'verbose_name': 'Ligne de facture', 'verbose_name_plural': 'Lignes de facture'},
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='montant',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'échéance"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de paiement'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Remise'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sous-total'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux TVA (%)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_emission',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'émission"),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total TTC'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.reservation', verbose_name='Réservation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('impaye', 'Impayée'), ('partiel', 'Paiement Partiel'), ('paye', 'Payée')], default='impaye', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice', verbose_name='Facture'),
        ),
    ]
