# Generated by Django 4.2.27 on 2026-02-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('billing', '0002_alter_invoice_options_alter_invoiceline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service', verbose_name='Service'),
        ),
    ]
