# Generated by Django 4.2.27 on 2026-02-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('billing', '0003_invoiceline_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitem', verbose_name='Article de Menu'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('impaye', 'Impayée'), ('paye', 'Payée')], default='impaye', max_length=20, verbose_name='Statut'),
        ),
    ]
