# Generated by Django 4.2.27 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cleaning_status',
            field=models.CharField(choices=[('sale', 'Sale'), ('propre', 'Propre'), ('inspectee', 'Inspectée')], default='propre', max_length=20),
        ),
    ]
