# Generated by Django 4.2.27 on 2026-02-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_cleaning_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du groupe (ex: Bloc A, 1er Étage)')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_groups/', verbose_name='Image de couverture')),
            ],
            options={
                'verbose_name': 'Groupe de chambres',
                'verbose_name_plural': 'Groupes de chambres',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomgroup', verbose_name='Groupe / Bloc'),
        ),
    ]
