# Generated by Django 4.2.27 on 2026-02-09 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_roomgroup_room_groupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='groupe',
        ),
        migrations.AlterField(
            model_name='room',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.roomcategory', verbose_name='Catégorie'),
        ),
        migrations.DeleteModel(
            name='RoomGroup',
        ),
    ]
