# Generated by Django 4.2.27 on 2026-02-04 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie de menu',
                'verbose_name_plural': 'Catégories de menu',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Numéro de table')),
                ('capacite', models.PositiveIntegerField(default=4, verbose_name='Capacité')),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('reservee', 'Réservée')], default='libre', max_length=10, verbose_name='Statut')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'article")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dining.menucategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Article de menu',
                'verbose_name_plural': 'Articles de menu',
            },
        ),
    ]
