# Generated by Django 4.2.27 on 2026-02-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
