# Generated by Django 4.2.27 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_solde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='piece_identite',
            field=models.ImageField(blank=True, null=True, upload_to='identites/', verbose_name="Pièce d'identité"),
        ),
    ]
