# Generated by Django 4.2.27 on 2026-02-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='mode_paiement',
            field=models.CharField(choices=[('cash', 'Cash'), ('banque', 'Banque'), ('post_paye', 'Post-payé')], default='cash', max_length=20),
        ),
    ]
