# Generated by Django 4.2.27 on 2026-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_mode_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('active', 'Active'), ('annulee', 'Annulée'), ('terminee', 'Terminée')], default='en_attente', max_length=20),
        ),
    ]
