# Generated by Django 4.2.27 on 2026-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant Payé (Cash)'),
        ),
    ]
