# Generated by Django 4.2.27 on 2026-02-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_expiration_visa',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration visa"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='numero_identite',
            field=models.CharField(blank=True, max_length=50, verbose_name="Numéro d'identité/Passeport"),
        ),
    ]
