# Generated by Django 4.2.27 on 2026-02-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('clients', 'Clients'), ('rooms', 'Chambres'), ('reservations', 'Réservations'), ('restaurant', 'Restauration'), ('transport', 'Transport'), ('complaints', 'Plaintes'), ('billing', 'Facturation'), ('settings', 'Système'), ('logs', 'Logs & Historique')], max_length=20),
        ),
    ]
