# Generated by Django 4.2.27 on 2026-02-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0003_roomgroup_room_groupe'),
        ('clients', '0003_alter_client_piece_identite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du plat')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix')),
                ('categorie', models.CharField(blank=True, max_length=50, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Photo du plat')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Détails / Ingrédients')),
                ('temps_cuisson', models.PositiveIntegerField(default=15, help_text='En minutes', verbose_name='Temps de cuisson')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_commande', models.CharField(choices=[('resident', 'Résident (Chambre)'), ('passage', 'Client de Passage')], default='passage', max_length=20, verbose_name='Type de client')),
                ('nom_client_passage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom (Client passage)')),
                ('numero_table', models.CharField(blank=True, max_length=10, null=True, verbose_name='Table')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_prepa', 'En préparation'), ('livre', 'Livré/Servi'), ('paye', 'Payé')], default='en_prepa', max_length=20, verbose_name='Statut')),
                ('paiement_effectue', models.BooleanField(default=False, verbose_name='Payé')),
                ('mode_paiement', models.CharField(choices=[('cash', 'Cash'), ('carte', 'Carte'), ('mobile', 'Mobile Money'), ('chambre', 'Sur la chambre'), ('abonnee', 'Abonné')], default='cash', max_length=20, verbose_name='Mode de paiement')),
                ('chambre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.room', verbose_name='Chambre')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem')),
            ],
        ),
    ]
