# Generated by Django 4.2.27 on 2026-02-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Prix Unitaire'),
        ),
    ]
