# Generated by Django 4.2.27 on 2026-02-03 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('view', 'Consultation'), ('error', 'Erreur'), ('system', 'Système')], db_index=True, max_length=20)),
                ('module', models.CharField(choices=[('clients', 'Clients'), ('rooms', 'Chambres'), ('reservations', 'Réservations'), ('restaurant', 'Restauration'), ('transport', 'Transport'), ('complaints', 'Plaintes'), ('billing', 'Facturation'), ('settings', 'Système'), ('auth', 'Authentification')], db_index=True, max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], db_index=True, default='info', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'module'], name='logs_activi_timesta_04b9a5_idx'), models.Index(fields=['user', '-timestamp'], name='logs_activi_user_id_bf0afe_idx')],
            },
        ),
    ]
